spring:
    application:
        name: demo
    
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:testdb;MODE=MySQL
        username: sa
        password:
    
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:                
                highlight_sql: true

logging:
    level:
        org:
            springframework:
                # orm.jpa.JpaTransactionManager: trace
                transaction:
                    interceptor: trace
                orm:
                    jpa: debug